### DISCUSSION TITLE
Alternative auth design for self-hosted shields

### DISCUSSION THREAD

**Discussion by coopernetes** [badges/shields#8581] [General] [answered]
Hi all! :wave: 
First off, thank you for the shields project! Our company uses shields internally as a self-hosted instance due to operating in an air-gapped environment and it's extremely helpful to build our badges for our internal CI and related services. That said, I have a predicament that I'd like to bring up to the community here.

One challenge we have is most of our systems that we are looking to generate badges for require authentication. Normally, this isn't a problem for shields since there is the concept of [server secrets](https://github.com/badges/shields/blob/master/doc/server-secrets.md) and the associated [auth helper](https://github.com/badges/shields/blob/ae58e4a2111b25a94bec1f3e477977d133a7e248/core/base-service/auth-helper.js). However, we don't have any mechanism of handling _multiple_ sets of credentials or tokens for a single type of badge. For example, I run many internal Maven repositories that are all privately secured. Alternatives are running individual shields instances per team/customer/"tenant", which isn't ideal. My intention is to run a single set of shields instances that can handle badges for all our internal development teams and thought it would be useful to have some sort of "auth delegation" to self-hosted shields.

My original idea was to extend the existing server secret model and allow selectable credentials to be used. Putting aside the authorization question of who is allowed to use a credential if it were made to be a drop-down, this made me think that maybe a better model would be to build in support for something like OIDC or SAML so that an individual user's access can be reused by shields and we could use a standard auth code OAuth flow. Of course, the systems I'm dealing with do not all support the newer authentication methods so I'm stuck with manual auth via LDAP, username+password, API tokens, etc.

This is my long-winded way of asking - Is this a useful enough feature for anyone else to use upstream or is there better alternative solutions we can use with the existing project? What my idea may look like:

```yaml
public:
  services:
      jenkins:
        authorizedOrigins: ...

# Retain global server secret config, act as default/fallback?
private:
  github: ... 
  jenkins: ...

  # Expose authDelegate=<id> as query param in badge generation
  delegates:
    <my-private-endpoints>:
      github: ...
    <other-private-endpoint>:
      github: ...
      jenkins: ... # If authDelegate=other-private-endpoint, use this token instead of private.jenkins
```

Alternatives considered:

* running multiple instances with their own unique server secrets. Doable but we now have to host shields in multiple places with only minor config differences (server secrets in this case)
* relaxing our access control to allow read-only access on a single set of secrets; we're a bit too security paranoid and I don't think this is suitable for all teams. 
* Allow tokens to be specified as query params for specific badges. This is obviously insecure and only really suitable in places where the hosting document (README) is behind its own private auth (ie. a private GitHub repo)

Just wondering if anyone else has experience in this area and can sanity check. I'm leaning towards either allowing tokens to be specified by users (bad), have a shields self-hosted instance accept multiple credential sets (better but still insecure because anyone can request to use another group's creds) or requiring our devs to run their own instance with their own server secrets (not ideal but minimal/no code changes needed to shields to support this)
