### ISSUE TITLE
Gitea Private Repos don't appear to work

### ISSUE THREAD

**Issue by chxseh** [badges/shields#10484]
### Are you experiencing an issue with...

My own instance of shields

### 🐞 Description

I'm unsure if I'm doing something wrong but I'm running a self-hosted instance of shields with docker:

```yaml
services:
  shields_io:
    container_name: shields.io
    env_file:
      - .env
    image: shieldsio/shields:next
    ports:
      - 2001:80/tcp
    restart: unless-stopped
networks: {}
```

```cs
GITEA_TOKEN=deadbeef
GITEA_ORIGINS=https://git.chse.dev
GH_TOKEN=ghp_asdf
```

I have a private repo where getting badges does not work. The token is valid and able to get data from the API.

<img width="1204" alt="image" src="https://github.com/user-attachments/assets/2836c3e9-410f-4581-ab86-62b90996770f">

### 🔗 Link to the badge

Public Repo: ![Gitea Stars](https://badges.chse.dev/gitea/stars/chase/infrastructure?gitea_url=https%3A%2F%2Fgit.chse.dev&style=flat) `https://badges.chse.dev/gitea/stars/chase/infrastructure?gitea_url=https%3A%2F%2Fgit.chse.dev&style=flat`

Private Repo: ![Gitea Stars](https://badges.chse.dev/gitea/stars/chase/short-links?gitea_url=https%3A%2F%2Fgit.chse.dev&style=flat) `https://badges.chse.dev/gitea/stars/chase/short-links?gitea_url=https%3A%2F%2Fgit.chse.dev&style=flat`
