### ISSUE TITLE
Github badges are intermittently inaccessible

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#1245]
I'm not sure whether this is due to one of the recent changes…

#1142 #1117 #1195 #1186 #1118 

…or simply #1119, which is a bug that causes a token to erroneously be considered exhausted once it's used for a search request.

People can't add new tokens either (#1243), exacerbating this slightly, but that will be fixed in #1038.

The first report was roughly 16 hours after deploy.

**Comment by paulmelnikow** [comment]
cc @espadrine

**Comment by paulmelnikow** [comment]
The badges are working again, and I think our "main" rate limit just reset:

```
core:
  remaining: 12489 of 12500
  reset: in an hour
search:
  remaining: 30 of 30
  reset: in a minute
graphql:
  remaining: 5000 of 5000
  reset: in an hour
```

**Comment by paulmelnikow** [comment]
Now intermittently broken, though plenty of rate limit left.

```
core:
  remaining: 12479 of 12500
  reset: in 18 minutes
search:
  remaining: 30 of 30
  reset: in a minute
graphql:
  remaining: 5000 of 5000
  reset: in an hour
```

Here's an example: https://img.shields.io/github/tag/expressjs/express.svg
![](https://img.shields.io/github/tag/expressjs/express.svg)
