### ISSUE TITLE
Feature Request: Endpoint YAML

### ISSUE THREAD

**Issue by SimpleBinary** [badges/shields#2964]
:clipboard: **Description**

I understand that the `Endpoint` badge is still in BETA, but it would be useful for the badge to use YAML as well as JSON.

It is just an idea, but I think that it would help some people who use YML more than JSON. Here is a comparison:

JSON

```json
{
  "schemaVersion": 1,
  "label": "hello",
  "message": "world",
  "color": "lightgrey"
}
```

YAML

```yaml
schemaVersion: 1
label: "hello"
message: "world"
color: "lightgrey"
```

- SimpleBinary
