### ISSUE TITLE
Inefficient caching of node_modules in CI

### ISSUE THREAD

**Issue by znarf** [badges/shields#4719]
Currently, in CircleCI configuration, we can see the following (simplified code).

```
    - restore_cache:
        keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}
    - run:
        name: Install dependencies
        command: npm ci

    - save_cache:
        paths:
          - node_modules
        key: v2-dependencies-{{ checksum "package-lock.json" }}
```

This doesn't make sense because the `npm ci` command is actually deleting the `node_modules` folder before proceeding. As outputted in every CI job:

```
npm WARN prepare removing existing node_modules/ before installation
```

Potential solutions:
- a) switch to `npm install`
- b) keep `npm ci` but cache the `~/.npm` folder
- c) remove caching (would save 30 seconds compared to existing)
