### ISSUE TITLE
Badge request: OpenBuildService

### ISSUE THREAD

**Issue by sp1ritCS** [badges/shields#5862]
:clipboard: **Description**

The OpenBuildService is the free Linux packaging platform from openSUSE.
For my usecase, I'd only need the build status from  one package in one repository, but it has a lot more api endpoints than that.

Example badge: https://img.shields.io/badge/openSUSE%20Tumbleweed-Succeeded-success

:link: **Data**

* API Doc: https://build.opensuse.org/apidocs/index
* The public buildservice instance: https://build.opensuse.org/
* Example status request: https://build.opensuse.org/build/hardware:razer/Debian_10/x86_64/openrazer/_status 

:microphone: **Motivation**

My usecase would be to show the build status of a package inside of a readme on github.
And if I click on it, it redirects to the download page of the package (https://software.opensuse.org/download/package?package=openrazer-meta&project=hardware%3Arazer).

**Comment by chris48s** [comment]
All requests to this API must use authentication. The example call you posted is a `401`.
Does authenticating only grant access to your own packages, or can a logged in user read other users packages? If logging in only allows access to your own packages, this probably isn't a service we could work with as credentials are provided via HTTP basic auth so the user would have to expose their login details.

**Comment by sp1ritCS** [comment]
> Does authenticating only grant access to your own packages, or can a logged in user read other users packages? 

no, you can access the result of any public package with any credentials.

But, feel a bit stupid that I havn't tested this, as I've just tried to do requests inside a browser I was already signed in 😅.

**Comment by chris48s** [comment]
> you can access the result of any public package with any credentials

In that case, it could work like bintray, symfony insight etc with a single set of shared credentials

**Comment by sp1ritCS** [comment]
I've gathered a bit more info:

Request via curl: `curl -u sp1rit:mypassword "https://api.opensuse.org/build/hardware:razer/Debian_10/x86_64/openrazer/_status"`

Different fields: `curl -u ${_username}:${_password} "https://${_instance}/build/${project}/${repository}/${arch}/${package}/_status"` (fields with `_` should be set by the environment)

The request returns 
```xml
<status package="openrazer" code="succeeded">
  <details></details>
</status>
```
the only interesting part is the `code` key from `<status>`. It can have different values. Here is the part of the css from the obs webinterface, that lists all build states aswell as their respective color.
```css
.build-state-succeeded {
 color:#008000
}
.build-state-building {
 background-color:#069
}
.build-state-scheduled {
 background-color:#007a7c
}
.build-state-signing,
.build-state-finished {
 color:black;
 background-color:#f0ad4e
}
.build-state-unresolvable,
.build-state-broken,
.build-state-failed {
 color:#dc3545
}
.build-state-unresolvable:hover,
.build-state-broken:hover,
.build-state-failed:hover {
 color:#dc3545
}
.build-state-disabled {
 color:#6c757d
}
.build-state-blocked {
 background-color:#6c757d
}
.build-state-scheduled-warning {
 background-color:#a50
}
.build-state-unknown {
 color:#a50
}
```
