### ISSUE TITLE
Fix DockerCloud tagged snapshot build

### ISSUE THREAD

**Issue by chris48s** [badges/shields#6850]
:clipboard: **Description**

- The action to build and push the 'next' tag when we push to master is working OK: https://github.com/badges/shields/actions/workflows/publish-docker-next.yml
- The action to push the snapshot tag when we push a tag is not working: https://github.com/badges/shields/actions/workflows/publish-docker-snapshot.yml (this should have run when we pushed https://github.com/badges/shields/releases/tag/server-2021-08-01 )

Not sure why, but the workflow is not starting at all so I guess there is probably something wrong with this line
https://github.com/badges/shields/blob/2e59a7a4cc82141b78330fdbb7a8238071642749/.github/workflows/publish-docker-snapshot.yml#L7
but I can't see what it is immediately and I haven't got time to debug it right now. I'll come back to it.

**Comment by nearcatch** [comment]
fwiw this action runs perfectly for me:
```yaml
name: Build and Publish Snapshot Docker Image
on: create

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/server-') }}
    steps:
      - name: Hello World
        run: echo Hello World
```
with the following commands:
```shell
git tag -a server-test -m server-test
git push origin server-test
```

So I don't think there's an issue with that step. There are a lot of failures of auto-close.yml at the same time as the one you're trying to troubleshoot - it almost looks like a 1 to 1 pairing. I'm not sure if it's possible for one workflow's failure to skip another though.
