### ISSUE TITLE
Style parameter is mandatory but README says otherwise

### ISSUE THREAD

**Issue by harryi3t** [badges/shields#695]
In the README file, passing the style `@flat` is shown not to be mandatory.

```javascript
var badge = require('gh-badges');
badge({ text: [ "build", "passed" ], colorscheme: "green" },
  function(svg, err) {
    // svg is a String… of your badge.
  });
```
and 
```bash
badge build passed :green .png > mybadge.png
```

should work. Both are not working for me.

I tried the command line help and saw the example provided
```
Usage: badge subject status [:colorscheme] [.output] [@style]
Or:    badge subject status right-color [left-color] [.output] [@style]

  colorscheme: one of brightgreen, green, yellow, yellowgreen, orange, red, blue, grey, gray, lightgrey, lightgray.
  left-color, right-color:
    #xxx (three hex digits)
    #xxxxxx (six hex digits)
    color (CSS color)
  output:
    svg, png, jpg, or gif

Eg: badge cactus grown :green @flat
```

The last line clearly mentions using `@flat`

I tried this and it worked (CLI). Now I needed to make the API also work. For this I went though the source code to find that the field is `badgeData.template`.

Please either update the readme file or update the code to take this parameter by default
