### ISSUE TITLE
Adding some more content for the docs for hosting on github

### ISSUE THREAD

**Issue by danielgroen** [badges/shields#8397]
Hi,

i wanted to host shield.io on my private server.

So i've read the following readme:
https://github.com/badges/shields/blob/master/doc/server-secrets.md#github

Here it was unclear if i needed to ajust the following lines:
https://github.com/badges/shields/blob/master/config/custom-environment-variables.yml#L82-L84

So what i've done is:

changed 
```yml
  gh_client_id: 'GH_CLIENT_ID'
  gh_client_secret: 'GH_CLIENT_SECRET'
  gh_token: 'GH_TOKEN'
```

to

```yml
  gh_client_id: private.GH_CLIENT_ID
  gh_client_secret: private.GH_CLIENT_SECRET
  gh_token: private.GH_TOKEN
```
Then i:
1. created a PAT with the right (full repo) permissions
2. created a repository secret GH_CLIENT_ID and filled in my client ID from (https://api.github.com/users/${myusername})
3. created a repository secret GH_CLIENT_SECRET and filled in my PAT name
4. created a repository secret GH_TOKEN and filled in my PAT value

However my badges won't work, can you tell what i am doing wrong, and maybe fill up the docs more for github private repos?:

The app i host is a forked one from your repo:
hosted on: https://githubshieldsio.herokuapp.com/
forked repo: https://github.com/danielgroen/shields

![afbeelding](https://user-images.githubusercontent.com/6578052/189868028-48ffc88b-f12c-43f2-b6f5-a9a06f6ad28b.png)
